# Generated by Django 4.2.13 on 2024-06-20 06:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0006_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='starting_time',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
