# Generated by Django 4.2.13 on 2024-06-20 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0007_alter_schedule_starting_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='starting_time',
            field=models.TimeField(),
        ),
    ]
