# Generated by Django 4.2.13 on 2024-06-25 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0008_alter_schedule_starting_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=0)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='new_app.schedule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='new_app.customer')),
            ],
        ),
    ]
