# Generated by Django 4.2.13 on 2024-06-29 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0010_alter_booking_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('M/C WITH GEAR', 'M/C WITH GEAR'), ('M/C WITHOUT GEAR', 'M/C WITHOUT GEAR'), ('LMV', 'LMV'), ('FOUR WHEELER', 'FOUR WHEELER')], max_length=50)),
                ('vehicle_no', models.CharField(max_length=10)),
                ('vehicle_name', models.CharField(max_length=40)),
                ('vehicle_model', models.CharField(max_length=40)),
                ('vehicle_brand', models.CharField(max_length=40)),
                ('problem', models.CharField(max_length=40)),
                ('date', models.DateField(auto_now=True)),
                ('cost', models.PositiveIntegerField(null=True)),
                ('status', models.CharField(choices=[('Repairing', 'Repairing'), ('Repairing Done', 'Repairing Done'), ('Released', 'Released')], default='Pending', max_length=50, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='new_app.customer')),
                ('workmanager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='new_app.workmanager')),
            ],
        ),
    ]
