# Generated by Django 4.2.13 on 2024-06-29 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0011_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='cost',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='vehicle_brand',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='vehicle_model',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='vehicle_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='vehicle_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
