# Generated by Django 4.2.13 on 2024-06-29 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0012_alter_request_cost_alter_request_vehicle_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='category',
            field=models.CharField(blank=True, choices=[('M/C WITH GEAR', 'M/C WITH GEAR'), ('M/C WITHOUT GEAR', 'M/C WITHOUT GEAR'), ('LMV', 'LMV'), ('FOUR WHEELER', 'FOUR WHEELER')], max_length=50, null=True),
        ),
    ]
