# Generated by Django 4.2.13 on 2024-06-29 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0013_alter_request_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='problem',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
