# Generated by Django 4.2.13 on 2024-07-02 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0014_alter_request_problem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Request',
            new_name='Work_creation',
        ),
    ]
