# Generated by Django 4.2.13 on 2024-07-02 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0015_rename_request_work_creation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Work_creation',
            new_name='Create_work',
        ),
    ]
