# Generated by Django 4.2.13 on 2024-07-02 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0016_rename_work_creation_create_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_work',
            name='status',
            field=models.CharField(blank=True, choices=[('Repairing', 'Repairing'), ('Repairing Done', 'Repairing Done'), ('Released', 'Released')], default='Pending', max_length=50, null=True),
        ),
    ]
