# Generated by Django 4.2.13 on 2024-07-04 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0017_alter_create_work_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_no', models.CharField(max_length=16)),
                ('cvv', models.CharField(max_length=3)),
                ('expiry', models.CharField(max_length=6)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='new_app.create_work')),
            ],
        ),
    ]
